FROM node:18-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm ci --only=production || npm i --production

# Copy source
COPY . .

# Expose port (Render uses $PORT env)
EXPOSE 4000

# Default command
CMD ["npm", "run", "socket-server"]
